### ISSUE TITLE
estimateHaze

### ISSUE THREAD

**Issue by BayAludra** [bleutner/RStoolbox#4]
Dear authors, 

first of all congratulations and thank you very much for this very nice package. 

I mainly used the package to calculate the atmospheric correction using the DOS method with LandSat8 images from 2014.

In Landsat8 images the DN values are encoded in 16bit and thus have the range 0 - 65535. Because of that the default value of the darkProp = 0.02 seems not to be appropriate since if running estimateHaze on gets the Warnings for each band: 

darkProp for band X was chosen too high. It exceeds the value range.

![haze1](https://cloud.githubusercontent.com/assets/16718648/12353536/36d81aee-bb90-11e5-9607-a419ae4c4a34.PNG)

Adjusting the value of darkProp to about 0.000025 fixes the problem and SHV values are evaluated properly. 
![haze2](https://cloud.githubusercontent.com/assets/16718648/12353541/4394d48e-bb90-11e5-8f09-f5915d703c29.PNG)

Nevertheless the provided examples are not working with my images and the manual setting of the darkProp parameter might not always be applicable. Thus, I was wondering if you could add some piece of code to check the DN values and adjust the default parameters somehow. 

In addition I am seeing that the following two corrections are giving exactly the same result: 

  ## Convert DN to top of atmosphere reflectance and brightness temperature
  lsat_ref <- radCor(lsat, metaData = metaData, method = "apref")

  hazeDN <- estimateHaze(lsat, hazeBands = 1:4, darkProp = 0.000025, plot = TRUE)
  lsat_sref <- radCor(lsat, metaData = metaData, method = "sdos",
                      hazeValues = hazeDN, hazeBands = 1:4)

So it seems that in my case the atmospheric correction is not doing anything which does not seem right. Do you have an idea where this could be coming from? Maybe it is somehow related to the issue with the very small haze values I mentioned. 

Thank you very much in advance for your help,
Hendrik

**Comment by bleutner** [comment]
Hi Hendrik, 

thanks for reporting. As a general note: I always recommend to make use of the Landsat LEDAPS Data by now *if* they are available, since this atmospheric correction is clearly superior to any DOS-based approach.

1. Estimate haze:
sensible identification of dark object based path radiance will likely always require some manual adjustments of darkProp. However, I have reworked the whole thing now and think it should be able to deal with any histogram now in a more sensible manner. 
What will happen now is that the 'darkProp' quantile of the histogram is selected as the maximum possible DN. Then, the function estimates the DN of steepest slope in the histogram lower that that DN as the final 'optimal' dark DN. The last step can be disabled by setting the new argument maxSlope to FALSE. However, i think that's a sensible way to do this. 

2. SDOS:
You were right. SDOS was not supported for Landsat 8, until now (but it didn't tell you that unfortunately, sorry). The issue here is, that we need the extraterrestrial irradiation for each band, which NASA does not provide anymore for Landsat 8 OLI. I have calculated these now (I'll do a blog post in some time with details) and according to some quick tests SDOS  should work just fine with these now.

**Comment by BayAludra** [comment]
Dear authors, 

thank you very much for taking care of this so quickly. I tested the new code and it now works fine with my images. Great!

In the meantime I spotted another issue. In Landsat 8 the RGB bands are 2:4 and when I tried to use only these three bands to estimate the haze some layers become filled with NAs. This is because the code can not handle when layer 1 is left out. If one uses 1:4 everything works fine but you might want to add some protection an a future release. 

By the way, are you planning to create a new version soon or should I keep using the development branch? 

Best
Hendrik

**Comment by bleutner** [comment]
Should be fixed now. 
I'm planning to release the next version some time next week. However, the development version should be reasonably save to use also.

**Comment by bleutner** [comment]
Fore the record: this is how LS8 Esun values were calculated:
http://bleutner.github.io/RStoolbox/r/2016/01/26/estimating-landsat-8-esun-values/

**Comment by BayAludra** [comment]
Wow, that is amazing. Thank you very much for the detailed explanation and implementation of all this stuff!
