### ISSUE TITLE
How to avoid excess of white space among plots

### ISSUE THREAD

**Issue by aloboa** [bleutner/RStoolbox#42]
I want to plot all bands of a multi-spectral image one next of the other.
I do it with RStoolbox::ggR() and gridExtra::grid.arrange(), but get
lots of wasted blank space:
```
require(raster)
require(gridExtra)
require(RStoolbox)

t <- theme(
  axis.text = element_blank(),
  axis.ticks = element_blank(),
  axis.title = element_blank())

r <- brick(array(rep(100,6*10^6),dim=c(1000,1000,6)))
a <- list(1:6,TRUE)
for(i in 1:6) a[[i]] <- ggR(r[[i]]) + t
grid.arrange(grobs=a)

```
Is there a way of avoiding so much space among band plots?
Perhaps a way not using grid.arrange() ?
Thanks

**Comment by bleutner** [comment]
### Alternative 1: for independent plot objects:
In general the spacing between independent plots depends on the dimensions of the plotting device (which you'll notice if you shrink or expand the graphics window). 
In such cases, I recommend to adapt and fix the device dimensions until the spacing corresponds to your desired outcome, e.g. 
```r
pdf("outfile.pdf", width=10, height=15)
grid.arrange(grobs=a)
dev.off()
```

It may be helpful to reduce or eliminate the plot margins by setting 
```r
theme(..., plot.margin=unit(c(0,0,0,0),"pt"))
```

### Alternative 2: using the facetting system of ggplot2
I've just pushed a new version of RStoolbox to this github repo. (Install current github master branch).
It allows you to do this:
```r
ggR(r, layer=1:6, geom_raster = TRUE) 
```
It adds a facet_wrap(~layerName) internally. Note that annotation_raster by design only allows to have the same layer over all panels. Therefore you will need to use geom_raster=TRUE. Alternative color scales can be added as usual, including the ability to hide the legend if its not meaningful to you. 

As always you can do it also by hand:
```r
df <- ggR(r, layer=1:6, geom_raster = TRUE, ggObj = FALSE) 
ggplot(df, aes(x=x,y=y,fill=value)) + geom_raster() + facet_grid(~layerName)
```

**Comment by aloboa** [comment]
I have an equivalent issue with ggRGB. Here I also have the problem of the axis labels:
```
a <- ggRGB(rlogo,r=1,g=2,b=3)
g <- list(a,a,a,a,a,a)
grid.arrange(grobs=g)
```
Any solution using RStoolbox?
