### ISSUE TITLE
blueish colors by default in ggR() if layers=1:3

### ISSUE THREAD

**Issue by aloboa** [bleutner/RStoolbox#45]
I find this weird:  
```
ggR(rlogo) #gray scale
s <- stack(rlogo,rlogo,rlogo)
ggR(s,layer=1:3, geom_raster = TRUE) #blue tones
ggR(s[[1]]) #gray scale
#hue, sat have no effect.
#To get gray tones I have to do:
ggR(s, layer=1:3, geom_raster = TRUE) + scale_fill_gradientn(colours = grey.colors(10))

```
why? I find it very inconvenient.  Any simpler way to avoid the bluish tones?
Thanks

**Comment by bleutner** [comment]
This is a limitation of `ggplot2::anotation_raster()`. 

The default of `ggR()` is to use `annotation_raster()` to add maps to plots, in order to keep the "fill" scale free for mapping meaningful variables to fill colours. However annotation_raster() does only allow the same annotation to be added to all facets, i.e. not what we want. Therefore we need to use geom_raster() in this case, which, however, brings with it the default blue color scale.

I agree that the blue default does not fit well with remote sensing data. I could force a different colorscale internally, but that would mean that everyone who adds his own scale_fill afterwards will be presented with this warning:  `for 'fill' is already present. Adding another scale for 'fill', which will replace the existing scale.`

Hence for now I'm planning no change here. Feel free to inquire with the ggplot2 developers to make annotation_raster respect facets. If they do, I'd be very happy to add it here as well.

**Comment by aloboa** [comment]
Could you perhaps change the default color before ggR() and then restore the "official" default?
I was thinking on something such as
```
scale_fill_gradientn_ori <- scale_fill_gradientn
scale_fill_gradientn <- function(...) scale_fill_gradientn(colours = grey.colors(10))
ggR(s,layer=1:3, geom_raster = TRUE)
scale_fill_gradientn <- scale_fill_gradientn_ori
```
but scale_fill_gradientn() is not the default color scale in geom_raster(), do you know which is it?
In that case, a workaround such as the one I suggest could be "built in" within ggR(geom_raster=TRUE)

Regarding the suggestion to ggplot2 devs, it makes more sense that you make a well reasoned inquire and I would vote for it. I worry not knowing what to say if the ask me questions.

**Comment by bleutner** [comment]
I don't think this would work, since the default scale lives in the namespace of ggplot2, not in the global environment. 

However, what you could do, is to add a shortcut function at the beginning of your scripts:
```r
library(RStoolbox); library(ggplot2)

ggR_grey <- function(...) { 
  ggR(..., geom_raster = TRUE) + scale_fill_gradientn(colors=grey.colors(100)) 
}

ggR_grey(lsat, 1:3)
```

I might include a shortcut function like this in the next package iteration.

**Comment by aloboa** [comment]
Works fine, thanks.
 It would be best having ggR_grey() as the default ggR()
(No reason to have a blue gradient as default in a RS tool).
