### ISSUE TITLE
coregisterImages tool manual page uses  contentious language

### ISSUE THREAD

**Issue by MatthiasSiewert** [bleutner/RStoolbox#63]
The terms 'master ' and 'slave' should be replaced by neutral terms to reflect current societal development.

**Comment by bleutner** [comment]
While the cause is just, I don't think this is going to make any difference whatsoever. In my opinion, such cosmetic activism is a distraction from the actual issues which would much rather need to be addressed. Nevertheless, I'm aware that some people feel and think otherwise, hence I followed your suggestion and renamed the arguments of `master` and `slave` to `ref` and `img`, respectively.
